apiVersion: v1
name: magda-ckan-connector
description: A Helm chart for Magda Ckan Connector
version: "0.0.57-0"
home: "https://github.com/magda-io/magda-ckan-connector"
sources: ["https://github.com/magda-io/magda-ckan-connector"]

